# Generated by Django 2.2.24 on 2022-05-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0002_auto_20220529_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
