# Generated by Django 2.2.24 on 2022-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0003_auto_20220529_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
