# Generated by Django 2.2.24 on 2022-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0007_auto_20220530_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, verbose_name='艺术门类')),
            ],
        ),
    ]
