# Generated by Django 2.2.24 on 2022-05-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0008_artcategoryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='art_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.ArtCategoryInfo', verbose_name='艺术门类'),
        ),
    ]
