# Generated by Django 2.2.24 on 2022-05-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0009_auto_20220530_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationtypeinfo',
            name='art_field',
        ),
        migrations.AddField(
            model_name='creationtypeinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.ArtCategoryInfo', verbose_name='艺术领域'),
        ),
        migrations.DeleteModel(
            name='ArtFieldInfo',
        ),
    ]
