# Generated by Django 2.2.24 on 2022-05-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0010_auto_20220530_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creationtypeinfo',
            old_name='creation_type',
            new_name='creationtype',
        ),
    ]
