# Generated by Django 2.2.24 on 2022-05-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0012_auto_20220530_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeworksinfo',
            name='art_creation_type',
        ),
        migrations.RemoveField(
            model_name='completeworksinfo',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='completeworksinfo',
            name='collection_museum',
        ),
        migrations.RemoveField(
            model_name='completeworksinfo',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='artcreationtype',
            field=models.CharField(max_length=16, null=True, verbose_name='创作类型'),
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='artistname',
            field=models.CharField(max_length=32, null=True, verbose_name='艺术家姓名'),
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='collectionmuseum',
            field=models.CharField(max_length=32, null=True, verbose_name='收藏博物馆'),
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='creationtime',
            field=models.CharField(max_length=32, null=True, verbose_name='创作时间'),
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.UserInfo', verbose_name='分享者'),
        ),
        migrations.AddField(
            model_name='completeworksinfo',
            name='uploadtime',
            field=models.DateField(null=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='creationtypeinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.ArtCategoryInfo', verbose_name='艺术门类'),
        ),
    ]
