# Generated by Django 2.2.24 on 2022-05-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0013_auto_20220530_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeworksinfo',
            name='sharer',
        ),
    ]
