# Generated by Django 2.2.24 on 2022-05-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0017_auto_20220531_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistinfo',
            old_name='artschool',
            new_name='artschools',
        ),
    ]
