# Generated by Django 2.2.24 on 2022-05-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0018_auto_20220531_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='birthtime',
            field=models.DateField(max_length=12, null=True, verbose_name='出生时间'),
        ),
    ]
