# Generated by Django 2.2.24 on 2022-06-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0019_auto_20220531_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='artcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.ArtCategoryInfo', verbose_name='艺术门类'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthtime',
            field=models.DateField(null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduatedfrom',
            field=models.CharField(max_length=32, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=16, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=16, null=True, verbose_name='昵称'),
        ),
    ]
