# Generated by Django 2.2.24 on 2022-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0021_auto_20220601_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeworksinfo',
            name='sharer',
            field=models.CharField(max_length=12, null=True, verbose_name='分享者'),
        ),
    ]
