# Generated by Django 2.2.24 on 2022-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0023_auto_20220606_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeworksinfo',
            name='sharer',
            field=models.CharField(max_length=12, null=True, verbose_name='分享者'),
        ),
    ]
