# Generated by Django 2.2.24 on 2022-06-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artWorks', '0024_auto_20220606_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeworksinfo',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artWorks.UserInfo', verbose_name='分享者'),
        ),
    ]
